apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=e72b44d7a404fc2f39a341221ad16f6ac82e2949
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=e72b44d7a404fc2f39a341221ad16f6ac82e2949

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: 414b18dd9eecfb93f0985eb63f21df21ed328f42

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../components/rh-certs

patches:
- target:
    kind: Deployment
    name: mintmaker-controller-manager
  patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/mintmaker.appstudio.redhat.com~1renovate-image
      value: "quay.io/lgallovi-test/mintmaker-renovate-image-test:update-test"
