apiVersion: v1
kind: Service
metadata:
  name: squid-service
  namespace: mintmaker
spec:
  selector:
    app: squid-proxy
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
  type: ClusterIP