apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
  namespace: mintmaker
data:
  squid.conf: |
    http_port 3128
    http_access allow all
    cache_mem 1 GB
    maximum_object_size_in_memory 2 MB
    cache_dir aufs /var/spool/squid 9000 16 256
    maximum_object_size 10 MB
    access_log stdio:/dev/stdout
    cache_log stdio:/dev/stdout
    coredump_dir /var/spool/squid
    via off
    forwarded_for delete

    acl github_api dstdomain api.github.com
    acl github_raw dstdomain raw.githubusercontent.com
    cache allow github_api
    cache allow github_raw
    refresh_pattern ^https://api\.github\.com/.* 180 100% 180 ignore-no-store ignore-private ignore-auth override-expire override-lastmod
    refresh_pattern ^https://raw\.githubusercontent\.com/.* 180 100% 180 ignore-no-store ignore-private ignore-auth override-expire override-lastmod